name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.1
  flutter_blue_plus: ^1.31.13
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  http: ^0.13.0
  path_provider: ^2.0.15
  image: ^4.1.3
  flutter_tts: ^3.8.5
  camera: ^0.10.5+9
  tflite_flutter: ^0.9.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  flutter_chat_ui: ^1.6.12
  flutter_chat_types: ^3.6.2
  file_picker: ^6.2.1
  uuid: ^3.0.7
  mime: ^1.0.5
  openai: ^1.0.0
  intl: ^0.17.0
  simple_animations: ^5.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/models/
  
  # Assets configuration removed as directories don't exist
  # Add asset directories here when created
